import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'hi', 'mr', 'gu', 'ta'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? mrText = '',
    String? guText = '',
    String? taText = '',
  }) =>
      [enText, hiText, mrText, guText, taText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // login
  {
    'i8l816dj': {
      'en': 'Login to Continue',
      'gu': 'ચાલુ રાખવા માટે લૉગિન કરો',
      'hi': 'जारी रखने के लिए लॉगिन करें',
      'mr': 'सुरू ठेवण्यासाठी लॉगिन करा',
      'ta': 'தொடர உள்நுழைக',
    },
    '63z0w37r': {
      'en': 'Email Address',
      'gu': 'ઈ - મેઈલ સરનામું',
      'hi': 'मेल पता',
      'mr': 'ईमेल पत्ता',
      'ta': 'மின்னஞ்சல் முகவரி',
    },
    '29jvyqdw': {
      'en': 'Password',
      'gu': 'પાસવર્ડ',
      'hi': 'पासवर्ड',
      'mr': 'पासवर्ड',
      'ta': 'கடவுச்சொல்',
    },
    'ezv2kv2b': {
      'en': 'Login',
      'gu': 'પ્રવેશ કરો',
      'hi': 'लॉग इन करें',
      'mr': 'लॉगिन करा',
      'ta': 'உள்நுழைய',
    },
    'buou4hjz': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // chat_2_Details
  {
    'y8nhnboo': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // chat_2_main
  {
    'iy44qcq0': {
      'en': 'My Chats',
      'gu': 'મારી ચેટ્સ',
      'hi': 'मेरी चैट',
      'mr': 'माझ्या गप्पा',
      'ta': 'எனது அரட்டைகள்',
    },
    'wrweq5sl': {
      'en': 'Below are your chats and group chats',
      'gu': 'નીચે તમારી ચેટ્સ અને ગ્રુપ ચેટ્સ છે',
      'hi': 'नीचे आपकी चैट और समूह चैट हैं',
      'mr': 'खाली तुमच्या चॅट्स आणि ग्रुप चॅट्स आहेत',
      'ta': 'உங்கள் அரட்டைகள் மற்றும் குழு அரட்டைகள் கீழே உள்ளன',
    },
    'b7g7faaz': {
      'en': '__',
      'gu': '__',
      'hi': '__',
      'mr': '__',
      'ta': '__',
    },
  },
  // chat_2_InviteUsers
  {
    '9nwm9mkm': {
      'en': 'Invite Friends',
      'gu': 'મિત્રોને આમંત્રિત કરો',
      'hi': 'मित्रों को आमंत्रित करें',
      'mr': 'मित्रांना आमंत्रित करा',
      'ta': 'நண்பர்களை அழைக்க',
    },
    '3wx8is7c': {
      'en': 'Selected',
      'gu': 'પસંદ કરેલ',
      'hi': 'चयनित',
      'mr': 'निवडले',
      'ta': 'தேர்ந்தெடுக்கப்பட்டது',
    },
    'mf5dyt5z': {
      'en': 'Invite Friends',
      'gu': 'મિત્રોને આમંત્રિત કરો',
      'hi': 'मित्रों को आमंत्रित करें',
      'mr': 'मित्रांना आमंत्रित करा',
      'ta': 'நண்பர்களை அழைக்க',
    },
    'a2dy5wct': {
      'en': 'Select users from below to start a chat.',
      'gu': 'ચેટ શરૂ કરવા માટે નીચેમાંથી વપરાશકર્તાઓને પસંદ કરો.',
      'hi': 'चैट शुरू करने के लिए नीचे से उपयोगकर्ताओं का चयन करें।',
      'mr': 'चॅट सुरू करण्यासाठी खालीलपैकी वापरकर्ते निवडा.',
      'ta': 'அரட்டையைத் தொடங்க கீழே உள்ள பயனர்களைத் தேர்ந்தெடுக்கவும்.',
    },
    'h91r3o2j': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // image_Details
  {
    'fkedh3xr': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // event_create
  {
    'xxmh4th8': {
      'en': 'Create Activity',
      'gu': 'પ્રવૃત્તિ બનાવો',
      'hi': 'गतिविधि बनाएँ',
      'mr': 'क्रियाकलाप तयार करा',
      'ta': 'செயல்பாட்டை உருவாக்கவும்',
    },
    'ao1fjtsx': {
      'en': 'You can fill out the elemements below to create an activity item.',
      'gu': 'તમે પ્રવૃત્તિ આઇટમ બનાવવા માટે નીચેના તત્વો ભરી શકો છો.',
      'hi': 'गतिविधि आइटम बनाने के लिए आप नीचे दिए गए तत्वों को भर सकते हैं।',
      'mr': 'क्रियाकलाप आयटम तयार करण्यासाठी तुम्ही खालील घटक भरू शकता.',
      'ta': 'செயல்பாட்டு உருப்படியை உருவாக்க கீழே உள்ள கூறுகளை நிரப்பலாம்.',
    },
    't2xrcx98': {
      'en': 'Activity Name...',
      'gu': 'પ્રવૃત્તિનું નામ...',
      'hi': 'गतिविधि का नाम...',
      'mr': 'क्रियाकलाप नाव...',
      'ta': 'செயல்பாட்டின் பெயர்...',
    },
    'zyjzilmk': {
      'en': 'Short Description of what is going on...',
      'gu': 'શું ચાલી રહ્યું છે તેનું ટૂંકું વર્ણન...',
      'hi': 'क्या हो रहा है इसका संक्षिप्त विवरण...',
      'mr': 'काय चालले आहे याचे थोडक्यात वर्णन...',
      'ta': 'என்ன நடக்கிறது என்பதற்கான சுருக்கமான விளக்கம்...',
    },
    'g5am0mq2': {
      'en': 'Upload Screenshot',
      'gu': 'સ્ક્રીનશોટ અપલોડ કરો',
      'hi': 'स्क्रीनशॉट अपलोड करें',
      'mr': 'स्क्रीनशॉट अपलोड करा',
      'ta': 'ஸ்கிரீன்ஷாட்டைப் பதிவேற்றவும்',
    },
    'hzxkc373': {
      'en': 'Create Activity',
      'gu': 'પ્રવૃત્તિ બનાવો',
      'hi': 'गतिविधि बनाएँ',
      'mr': 'क्रियाकलाप तयार करा',
      'ta': 'செயல்பாட்டை உருவாக்கவும்',
    },
    'uxpmt26l': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // timetable
  {
    '77z8rp4d': {
      'en': 'Timetable',
      'gu': 'સમયપત્રક',
      'hi': 'समय सारणी',
      'mr': 'वेळापत्रक',
      'ta': 'கால அட்டவணை',
    },
    'ywobh8lg': {
      'en': 'Monday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'tnk6jbin': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    '0ciyhwi9': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'oven3yg9': {
      'en': 'Tuesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'mpnrl62e': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'nvtp9dkp': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ch0dj97d': {
      'en': 'Wednesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'tqi96tsh': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    '2a4bmpen': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '2zsuzq3x': {
      'en': 'Thursday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '6e88q6fw': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'm1nf2t0a': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '42tk6btg': {
      'en': 'Friday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'twqfcw0m': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'czxnmqes': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'x1084ygy': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // guest_visit
  {
    'ijyhuam2': {
      'en': 'back',
      'gu': 'પાછા',
      'hi': 'पीछे',
      'mr': 'परत',
      'ta': 'மீண்டும்',
    },
    'npk8122q': {
      'en': 'Welcome Guest',
      'gu': 'સ્વાગત મહેમાન',
      'hi': 'इच्छित अतिथि',
      'mr': 'स्वागत अतिथी',
      'ta': 'வரவேற்பு விருந்தினர்',
    },
    'lxgntcri': {
      'en': 'Actions',
      'gu': 'ક્રિયાઓ',
      'hi': 'कार्रवाई',
      'mr': 'क्रिया',
      'ta': 'செயல்கள்',
    },
    'wx32rj9p': {
      'en': 'Post',
      'gu': 'પોસ્ટ',
      'hi': 'डाक',
      'mr': 'पोस्ट',
      'ta': 'அஞ்சல்',
    },
    '2htsv65t': {
      'en': 'Students',
      'gu': 'વિદ્યાર્થીઓ',
      'hi': 'छात्र',
      'mr': 'विद्यार्थीच्या',
      'ta': 'மாணவர்கள்',
    },
    'fljjz39z': {
      'en': 'Teachers',
      'gu': 'શિક્ષકો',
      'hi': 'शिक्षकों की',
      'mr': 'शिक्षक',
      'ta': 'ஆசிரியர்கள்',
    },
    '764fgqk9': {
      'en': 'Notifications',
      'gu': 'સૂચનાઓ',
      'hi': 'सूचनाएं',
      'mr': 'अधिसूचना',
      'ta': 'அறிவிப்புகள்',
    },
    'y5i02x83': {
      'en': 'Below is a list of your activities.',
      'gu': 'નીચે તમારી પ્રવૃત્તિઓની સૂચિ છે.',
      'hi': 'नीचे आपकी गतिविधियों की एक सूची है.',
      'mr': 'खाली तुमच्या क्रियाकलापांची यादी आहे.',
      'ta': 'உங்கள் செயல்பாடுகளின் பட்டியல் கீழே உள்ளது.',
    },
    '3rpcq3h6': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // PDF_upload
  {
    'icaazs3t': {
      'en': 'Upload PDF file',
      'gu': 'પીડીએફ ફાઈલ અપલોડ કરો',
      'hi': 'पीडीएफ फाइल अपलोड करें',
      'mr': 'पीडीएफ फाइल अपलोड करा',
      'ta': 'PDF கோப்பை பதிவேற்றவும்',
    },
    '336ok8o2': {
      'en': 'Section A',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zbw0zp8t': {
      'en': 'Section B',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '4nxkyld7': {
      'en': 'Section C',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'yjkxvl0y': {
      'en': 'Section D',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'kxbs3oh8': {
      'en': 'Select section..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '131hzixm': {
      'en': 'Search for an item...',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zt7jy6wj': {
      'en': 'File Name',
      'gu': 'ફાઈલનું નામ',
      'hi': 'फ़ाइल का नाम',
      'mr': 'फाईलचे नाव',
      'ta': 'கோப்பு பெயர்',
    },
    'f5dkmq67': {
      'en': 'Select PDF',
      'gu': 'પીડીએફ પસંદ કરો',
      'hi': 'पीडीएफ का चयन करें',
      'mr': 'पीडीएफ निवडा',
      'ta': 'PDF ஐத் தேர்ந்தெடுக்கவும்',
    },
    'edn3v00j': {
      'en': 'Upload PDF',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    '79h4lymn': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // PDF_view
  {
    'n1jkmjz0': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // Home
  {
    'cf1ihxis': {
      'en': 'Timetable',
      'gu': 'અનુસૂચિ',
      'hi': 'अनुसूची',
      'mr': 'वेळापत्रक',
      'ta': 'அட்டவணை',
    },
    '7umbudy8': {
      'en': 'Schedule Student',
      'gu': 'અનુસૂચિ',
      'hi': 'अनुसूची',
      'mr': 'वेळापत्रक',
      'ta': 'அட்டவணை',
    },
    'dewy9wwz': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'or9z4lf3': {
      'en': 'Messages',
      'gu': 'સંદેશાઓ',
      'hi': 'संदेशों',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'bof74sfy': {
      'en': 'Student Resources',
      'gu': 'વિદ્યાર્થી સંસાધનો',
      'hi': 'छात्र संसाधन',
      'mr': 'विद्यार्थी संसाधने',
      'ta': 'மாணவர் வளங்கள்',
    },
    'hqbyi2g4': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'olq81qkj': {
      'en': 'Notice',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'zdv9y538': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    '9shiocat': {
      'en': 'Posts',
      'gu': 'પોસ્ટ્સ',
      'hi': 'पदों',
      'mr': 'पोस्ट',
      'ta': 'இடுகைகள்',
    },
    'gkk0kpaj': {
      'en': 'Student Profile',
      'gu': 'વિદ્યાર્થી પ્રોફાઇલ',
      'hi': 'छात्र प्रोफाइल',
      'mr': 'विद्यार्थी प्रोफाइल',
      'ta': 'மாணவர் சுயவிவரம்',
    },
    '6fbcgs5k': {
      'en': 'Gallery',
      'gu': 'ગેલેરી',
      'hi': 'गैलरी',
      'mr': 'गॅलरी',
      'ta': 'கேலரி',
    },
    'iy593hf1': {
      'en': 'Faculty',
      'gu': 'ફેકલ્ટી',
      'hi': 'संकाय',
      'mr': 'विद्याशाखा',
      'ta': 'ஆசிரியர்',
    },
    'h75u2jp2': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // Posts
  {
    'vevmnns6': {
      'en': 'Events',
      'gu': 'ઘટનાઓ',
      'hi': 'आयोजन',
      'mr': 'कार्यक्रम',
      'ta': 'நிகழ்வுகள்',
    },
    '96qdq2sk': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // Circular_create
  {
    '80ctk79u': {
      'en': 'Add Circular',
      'gu': 'પરિપત્ર ઉમેરો',
      'hi': 'परिपत्र जोड़ें',
      'mr': 'परिपत्रक जोडा',
      'ta': 'சுற்றறிக்கையைச் சேர்க்கவும்',
    },
    'o8es2yoo': {
      'en': 'You can fill out the elements below to create an Circular item.',
      'gu': 'પરિપત્ર આઇટમ બનાવવા માટે તમે નીચેના તત્વો ભરી શકો છો.',
      'hi':
          'आप एक परिपत्र आइटम बनाने के लिए नीचे दिए गए तत्वों को भर सकते हैं।',
      'mr': 'परिपत्रक आयटम तयार करण्यासाठी तुम्ही खालील घटक भरू शकता.',
      'ta': 'ஒரு வட்ட உருப்படியை உருவாக்க கீழே உள்ள கூறுகளை நிரப்பலாம்.',
    },
    'n402oheg': {
      'en': 'Title',
      'gu': 'શીર્ષક',
      'hi': 'शीर्षक',
      'mr': 'शीर्षक',
      'ta': 'தலைப்பு',
    },
    'e2m36iic': {
      'en': 'Description',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zwchtv01': {
      'en': '',
      'gu': 'શું ચાલી રહ્યું છે તેનું ટૂંકું વર્ણન...',
      'hi': 'क्या हो रहा है इसका संक्षिप्त विवरण...',
      'mr': 'काय चालले आहे याचे थोडक्यात वर्णन...',
      'ta': 'என்ன நடக்கிறது என்பதற்கான சுருக்கமான விளக்கம்...',
    },
    '75fb4wu3': {
      'en': 'Select PDF',
      'gu': 'પીડીએફ પસંદ કરો',
      'hi': 'पीडीएफ का चयन करें',
      'mr': 'पीडीएफ निवडा',
      'ta': 'PDF ஐத் தேர்ந்தெடுக்கவும்',
    },
    'q1f171wn': {
      'en': 'Confirm Circular',
      'gu': 'પરિપત્રની પુષ્ટિ કરો',
      'hi': 'परिपत्र की पुष्टि करें',
      'mr': 'परिपत्रकाची पुष्टी करा',
      'ta': 'சுற்றறிக்கையை உறுதிப்படுத்தவும்',
    },
    '7w64vkjm': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // Circulars
  {
    'xznpe2pe': {
      'en': 'Notice',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'i5sy8w3w': {
      'en': 'View PDF',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zycgf5y9': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // teacher_list
  {
    'u21vd4m0': {
      'en': 'Teachers',
      'gu': 'શિક્ષકો',
      'hi': 'शिक्षकों की',
      'mr': 'शिक्षक',
      'ta': 'ஆசிரியர்கள்',
    },
    'i31qsh1x': {
      'en': 'search...',
      'gu': 'શોધ...',
      'hi': 'खोज...',
      'mr': 'शोधा...',
      'ta': 'தேடு...',
    },
    '4a9y6d6l': {
      'en': 'Search',
      'gu': 'શોધો',
      'hi': 'खोज',
      'mr': 'शोधा',
      'ta': 'தேடு',
    },
    'u51dn2qh': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // update_event
  {
    '18ydyw5h': {
      'en': 'Update Activity',
      'gu': 'પ્રવૃત્તિ બનાવો',
      'hi': 'गतिविधि बनाएँ',
      'mr': 'क्रियाकलाप तयार करा',
      'ta': 'செயல்பாட்டை உருவாக்கவும்',
    },
    'sg2lvtgq': {
      'en': 'You can fill out the elements below to update an activity item.',
      'gu': 'તમે પ્રવૃત્તિ આઇટમ બનાવવા માટે નીચેના તત્વો ભરી શકો છો.',
      'hi': 'गतिविधि आइटम बनाने के लिए आप नीचे दिए गए तत्वों को भर सकते हैं।',
      'mr': 'क्रियाकलाप आयटम तयार करण्यासाठी तुम्ही खालील घटक भरू शकता.',
      'ta': 'செயல்பாட்டு உருப்படியை உருவாக்க கீழே உள்ள கூறுகளை நிரப்பலாம்.',
    },
    '4oa4i8xk': {
      'en': 'Activity Name...',
      'gu': 'પ્રવૃત્તિનું નામ...',
      'hi': 'गतिविधि का नाम...',
      'mr': 'क्रियाकलाप नाव...',
      'ta': 'செயல்பாட்டின் பெயர்...',
    },
    '5bny77oi': {
      'en': 'Short Description of what is going on...',
      'gu': 'શું ચાલી રહ્યું છે તેનું ટૂંકું વર્ણન...',
      'hi': 'क्या हो रहा है इसका संक्षिप्त विवरण...',
      'mr': 'काय चालले आहे याचे थोडक्यात वर्णन...',
      'ta': 'என்ன நடக்கிறது என்பதற்கான சுருக்கமான விளக்கம்...',
    },
    'hxuhrdq9': {
      'en': 'Upload Screenshot',
      'gu': 'સ્ક્રીનશોટ અપલોડ કરો',
      'hi': 'स्क्रीनशॉट अपलोड करें',
      'mr': 'स्क्रीनशॉट अपलोड करा',
      'ta': 'ஸ்கிரீன்ஷாட்டைப் பதிவேற்றவும்',
    },
    'znzfv872': {
      'en': 'Update Activity',
      'gu': 'અપડેટ પ્રવૃત્તિ',
      'hi': 'अद्यतन गतिविधि',
      'mr': 'क्रियाकलाप अद्यतनित करा',
      'ta': 'செயல்பாட்டைப் புதுப்பிக்கவும்',
    },
    'vn4l2j6a': {
      'en': 'Delete Activity',
      'gu': 'અપડેટ પ્રવૃત્તિ',
      'hi': 'अद्यतन गतिविधि',
      'mr': 'क्रियाकलाप अद्यतनित करा',
      'ta': 'செயல்பாட்டைப் புதுப்பிக்கவும்',
    },
    '7boab0mi': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // HomeCopy
  {
    'jbw5tdrt': {
      'en': 'Log Out',
      'gu': 'લૉગ આઉટ',
      'hi': 'लॉग आउट',
      'mr': 'बाहेर पडणे',
      'ta': 'வெளியேறு',
    },
    '9jqn5f08': {
      'en': 'Schedule',
      'gu': 'અનુસૂચિ',
      'hi': 'अनुसूची',
      'mr': 'वेळापत्रक',
      'ta': 'அட்டவணை',
    },
    'e7ypzxul': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'svhzk1cd': {
      'en': 'Messages',
      'gu': 'સંદેશાઓ',
      'hi': 'संदेशों',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'zpq31y91': {
      'en': 'Student Resources',
      'gu': 'વિદ્યાર્થી સંસાધનો',
      'hi': 'छात्र संसाधन',
      'mr': 'विद्यार्थी संसाधने',
      'ta': 'மாணவர் வளங்கள்',
    },
    'zkgd4lvg': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'rtbrndta': {
      'en': 'Notice',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'avq6hs5r': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    '5hgmxwg0': {
      'en': 'Posts',
      'gu': 'પોસ્ટ્સ',
      'hi': 'पदों',
      'mr': 'पोस्ट',
      'ta': 'இடுகைகள்',
    },
    '87vaoat7': {
      'en': 'Student Profile',
      'gu': 'વિદ્યાર્થી પ્રોફાઇલ',
      'hi': 'छात्र प्रोफाइल',
      'mr': 'विद्यार्थी प्रोफाइल',
      'ta': 'மாணவர் சுயவிவரம்',
    },
    '8pdox0yu': {
      'en': 'Gallery',
      'gu': 'ગેલેરી',
      'hi': 'गैलरी',
      'mr': 'गॅलरी',
      'ta': 'கேலரி',
    },
    'eytry80n': {
      'en': 'Faculty',
      'gu': 'ફેકલ્ટી',
      'hi': 'संकाय',
      'mr': 'विद्याशाखा',
      'ta': 'ஆசிரியர்',
    },
    'dp6ox1n0': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // student_list
  {
    '5a7ekyp8': {
      'en': 'Students',
      'gu': 'વિદ્યાર્થીઓ',
      'hi': 'छात्र',
      'mr': 'विद्यार्थीच्या',
      'ta': 'மாணவர்கள்',
    },
    'uqayt5kf': {
      'en': 'search...',
      'gu': 'શોધ...',
      'hi': 'खोज...',
      'mr': 'शोधा...',
      'ta': 'தேடு...',
    },
    '79ejclth': {
      'en': 'Search',
      'gu': 'શોધો',
      'hi': 'खोज',
      'mr': 'शोधा',
      'ta': 'தேடு',
    },
    'sx4hmxu5': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // update_circular
  {
    'xacyymg1': {
      'en': 'Update Circular',
      'gu': 'પ્રવૃત્તિ બનાવો',
      'hi': 'गतिविधि बनाएँ',
      'mr': 'क्रियाकलाप तयार करा',
      'ta': 'செயல்பாட்டை உருவாக்கவும்',
    },
    'b410bsnw': {
      'en': 'You can fill out the elements below to update an Circular item.',
      'gu': 'તમે પ્રવૃત્તિ આઇટમ બનાવવા માટે નીચેના તત્વો ભરી શકો છો.',
      'hi': 'गतिविधि आइटम बनाने के लिए आप नीचे दिए गए तत्वों को भर सकते हैं।',
      'mr': 'क्रियाकलाप आयटम तयार करण्यासाठी तुम्ही खालील घटक भरू शकता.',
      'ta': 'செயல்பாட்டு உருப்படியை உருவாக்க கீழே உள்ள கூறுகளை நிரப்பலாம்.',
    },
    'ohci27wq': {
      'en': 'Activity Name...',
      'gu': 'પ્રવૃત્તિનું નામ...',
      'hi': 'गतिविधि का नाम...',
      'mr': 'क्रियाकलाप नाव...',
      'ta': 'செயல்பாட்டின் பெயர்...',
    },
    'ncfuezkx': {
      'en': 'Description',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'y20v3yaw': {
      'en': 'Short Description of what is going on...',
      'gu': 'શું ચાલી રહ્યું છે તેનું ટૂંકું વર્ણન...',
      'hi': 'क्या हो रहा है इसका संक्षिप्त विवरण...',
      'mr': 'काय चालले आहे याचे थोडक्यात वर्णन...',
      'ta': 'என்ன நடக்கிறது என்பதற்கான சுருக்கமான விளக்கம்...',
    },
    'eqjtruav': {
      'en': 'Update Circular',
      'gu': 'અપડેટ પ્રવૃત્તિ',
      'hi': 'अद्यतन गतिविधि',
      'mr': 'क्रियाकलाप अद्यतनित करा',
      'ta': 'செயல்பாட்டைப் புதுப்பிக்கவும்',
    },
    'shdlqioo': {
      'en': 'Delete Circular',
      'gu': 'અપડેટ પ્રવૃત્તિ',
      'hi': 'अद्यतन गतिविधि',
      'mr': 'क्रियाकलाप अद्यतनित करा',
      'ta': 'செயல்பாட்டைப் புதுப்பிக்கவும்',
    },
    '1p75sry2': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // create_schedule
  {
    '0tt0wzb5': {
      'en': 'Schedule for student',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '83zvasam': {
      'en': 'Select Student',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'c4qwgw1d': {
      'en': 'Monday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'nf5gbaxz': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    '915n11kz': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ddhwxsch': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'vxevbbwj': {
      'en': 'Tuesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'igthn1fu': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'jo69v5ig': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'dm9xnqdc': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'rjxs73g2': {
      'en': 'Wednesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'u8qppi1d': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    '313nzw7i': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'x0tuns4x': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zv4a9p2a': {
      'en': 'Thursday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ji6gvo94': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'smhh6jz0': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ou6b6im1': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'e4zhwadn': {
      'en': 'Friday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'xsatch1v': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    '7f7pc09a': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'jqolafms': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'u01nlm4p': {
      'en': 'Confirm Schedule',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '5t84d67o': {
      'en': 'Home',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // scheduled_stu_list
  {
    'za82r8f9': {
      'en': 'Students',
      'gu': 'વિદ્યાર્થીઓ',
      'hi': 'छात्र',
      'mr': 'विद्यार्थीच्या',
      'ta': 'மாணவர்கள்',
    },
    '6hsiitjm': {
      'en': 'search...',
      'gu': 'શોધ...',
      'hi': 'खोज...',
      'mr': 'शोधा...',
      'ta': 'தேடு...',
    },
    'kseqklo5': {
      'en': 'Search',
      'gu': 'શોધો',
      'hi': 'खोज',
      'mr': 'शोधा',
      'ta': 'தேடு',
    },
    'oybv4f85': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // syllabusSectionA
  {
    'r5kzhc5i': {
      'en': 'PDF',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '3v82o261': {
      'en': 'Videos',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'xcf6tvib': {
      'en': 'References',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'jq2d4dzl': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // videos_upload
  {
    'xh6oah70': {
      'en': 'Upload Video Link',
      'gu': 'પીડીએફ ફાઈલ અપલોડ કરો',
      'hi': 'पीडीएफ फाइल अपलोड करें',
      'mr': 'पीडीएफ फाइल अपलोड करा',
      'ta': 'PDF கோப்பை பதிவேற்றவும்',
    },
    'urm6dfy7': {
      'en': 'Section A',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '42is8e5w': {
      'en': 'Section B',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ao0nmsfm': {
      'en': 'Section C',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'axvh41eq': {
      'en': 'Section D',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'fbg44vqo': {
      'en': 'Select section..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'kkqmxl1p': {
      'en': 'Search for an item...',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'l0fu09ap': {
      'en': 'Video Title',
      'gu': 'ફાઈલનું નામ',
      'hi': 'फ़ाइल का नाम',
      'mr': 'फाईलचे नाव',
      'ta': 'கோப்பு பெயர்',
    },
    'oxora2pd': {
      'en': 'Video Link',
      'gu': 'ફાઈલનું નામ',
      'hi': 'फ़ाइल का नाम',
      'mr': 'फाईलचे नाव',
      'ta': 'கோப்பு பெயர்',
    },
    'ae2c062m': {
      'en': 'Upload Video',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    'm5uqz3q2': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // syllabusSectionC
  {
    '8ocx66h7': {
      'en': 'PDF',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'lnbav008': {
      'en': 'Videos',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'g74ufpv5': {
      'en': 'References',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    '8a141np4': {
      'en': 'Home',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // syllabusSectionB
  {
    'tw4goil9': {
      'en': 'PDF',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '1d4rfmi6': {
      'en': 'Videos',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'k0pr8h2j': {
      'en': 'References',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'jopjfpk2': {
      'en': 'Home',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // ReferenceBooks_BasedOnSection
  {
    '56ujikio': {
      'en': 'Section A',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '3cyhdhmx': {
      'en': 'Section B',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'km4fzzjw': {
      'en': 'Section C',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'vndcrcgj': {
      'en': 'Section D',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'uv3uyogr': {
      'en': 'Select Section',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    'swa6d9wy': {
      'en': 'Home',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // PDF_uploadEdit
  {
    'fxiw7x3w': {
      'en': 'Edit PDF file',
      'gu': 'પીડીએફ ફાઈલ અપલોડ કરો',
      'hi': 'पीडीएफ फाइल अपलोड करें',
      'mr': 'पीडीएफ फाइल अपलोड करा',
      'ta': 'PDF கோப்பை பதிவேற்றவும்',
    },
    'qynu8048': {
      'en': 'Section A',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'qcfr83rr': {
      'en': 'Section B',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'k424hht4': {
      'en': 'Section C',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'p2mnuvmk': {
      'en': 'Section D',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'bkm25vex': {
      'en': 'Select section..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'dkqmxz2f': {
      'en': 'Search for an item...',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '5anwzxqw': {
      'en': 'File Name',
      'gu': 'ફાઈલનું નામ',
      'hi': 'फ़ाइल का नाम',
      'mr': 'फाईलचे नाव',
      'ta': 'கோப்பு பெயர்',
    },
    'rkavv93o': {
      'en': 'Update PDF',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    'y2fzift2': {
      'en': 'Delete PDF',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    'xnii81ky': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // videos_uploadEdit
  {
    '5ej7t84w': {
      'en': 'Edit Video Link',
      'gu': 'પીડીએફ ફાઈલ અપલોડ કરો',
      'hi': 'पीडीएफ फाइल अपलोड करें',
      'mr': 'पीडीएफ फाइल अपलोड करा',
      'ta': 'PDF கோப்பை பதிவேற்றவும்',
    },
    '5ltqzfix': {
      'en': 'Section A',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'td18knkx': {
      'en': 'Section B',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'sjwwulqd': {
      'en': 'Section C',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'izw6w3bt': {
      'en': 'Section D',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'aejf2wzb': {
      'en': 'Select section..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '4m7vrqf9': {
      'en': 'Search for an item...',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'yf6ocyn2': {
      'en': 'Video Title',
      'gu': 'ફાઈલનું નામ',
      'hi': 'फ़ाइल का नाम',
      'mr': 'फाईलचे नाव',
      'ta': 'கோப்பு பெயர்',
    },
    '9lvh4czp': {
      'en': 'Update video',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    'a0iai793': {
      'en': 'Delete video',
      'gu': 'પીડીએફ અપલોડ કરો',
      'hi': 'पीडीएफ अपलोड करें',
      'mr': 'PDF अपलोड करा',
      'ta': 'PDF ஐ பதிவேற்றவும்',
    },
    'eysnmbq7': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // circular_PDFView
  {
    'jq78hx0h': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // update_schedule
  {
    'ojzyohxy': {
      'en': 'Update Schedule',
      'gu': 'પાછા',
      'hi': 'पीछे',
      'mr': 'परत',
      'ta': 'மீண்டும்',
    },
    '6s3sblkr': {
      'en': 'Monday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'cg6rc6ij': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'ma1vi7ku': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'j1z1nbd6': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '7g028sug': {
      'en': 'Tuesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '97savkvb': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'o1nwvyx1': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '1br80ewm': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'lehawb4q': {
      'en': 'Wednesday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'k6zb5kwl': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'q12vvjh1': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '807u4lb4': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'wwu1murw': {
      'en': 'Thursday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '03ag0r76': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'gy6w8i69': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'lcd74630': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'eo4o08ue': {
      'en': 'Friday',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'dfa1si4y': {
      'en': '9:30 AM',
      'gu': '8:15am - 9:00am',
      'hi': 'प्रातः 8:15 - प्रातः 9:00 बजे तक',
      'mr': 'सकाळी ८:१५ ते ९:००',
      'ta': 'காலை 8:15 - 9:00 மணி',
    },
    'de2b6lh8': {
      'en': '-',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '0o5whofl': {
      'en': 'Enter Class name..',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'v3wv88rp': {
      'en': 'Confirm Update ',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'a2o2mlv9': {
      'en': 'Delete schedule',
      'gu': 'અપડેટ પ્રવૃત્તિ',
      'hi': 'अद्यतन गतिविधि',
      'mr': 'क्रियाकलाप अद्यतनित करा',
      'ta': 'செயல்பாட்டைப் புதுப்பிக்கவும்',
    },
    'r4v31pvq': {
      'en': 'Home',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // create_new_account
  {
    'ffb6fyuw': {
      'en': 'Name',
      'gu': 'નામ',
      'hi': 'नाम',
      'mr': 'नाव',
      'ta': 'பெயர்',
    },
    '4e14do04': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '3tjgb47n': {
      'en': 'Male',
      'gu': 'પુરુષ',
      'hi': 'पुरुष',
      'mr': 'पुरुष',
      'ta': 'ஆண்',
    },
    '6n6msmrd': {
      'en': 'Female',
      'gu': 'સ્ત્રી',
      'hi': 'महिला',
      'mr': 'स्त्री',
      'ta': 'பெண்',
    },
    '114r8oon': {
      'en': 'Select Gender',
      'gu': 'લિંગ પસંદ કરો',
      'hi': 'लिंग चुनें',
      'mr': 'लिंग निवडा',
      'ta': 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
    },
    'z5qq92ib': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'crzn8v76': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'pt7w66vj': {
      'en': 'Place & Country of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'wdf7cese': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    '6fdsf8xu': {
      'en': 'Aadhar card no.',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'dyy8h383': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    '2kf0jiw8': {
      'en': 'Blood Group',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'bepo2l61': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'jsqkxbc3': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    '4h704ato': {
      'en': 'Number which is to be conntected with portal',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'lv5hcfd6': {
      'en': 'Address',
      'gu': 'સરનામું',
      'hi': 'पता',
      'mr': 'पत्ता',
      'ta': 'முகவரி',
    },
    'd6ad6u3b': {
      'en': 'Identity Proof',
      'gu': 'ઓળખ પુરાવો',
      'hi': 'पहचान प्रमाण',
      'mr': 'ओळख पुरावा',
      'ta': 'அடையாளச் சான்று',
    },
    'aiqxfki0': {
      'en': 'Student Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    '3kaehu6d': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    '995x4rol': {
      'en': 'Disability',
      'gu': 'અપંગતા',
      'hi': 'विकलांगता',
      'mr': 'दिव्यांग',
      'ta': 'இயலாமை',
    },
    'm0tvuhqs': {
      'en': 'Medical Paper',
      'gu': 'મેડિકલ પેપર',
      'hi': 'मेडिकल पेपर',
      'mr': 'वैद्यकीय पेपर',
      'ta': 'மருத்துவ தாள்',
    },
    'luv3ne2q': {
      'en': 'Father\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    'saa3xo5k': {
      'en': 'Father Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    '628t5w53': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'xnaz6wky': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'yksmyfcq': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '0pnl20w1': {
      'en': 'Mother\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    'fxsm5zet': {
      'en': 'Mother Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    'dksvz23q': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '19r151e9': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '4y4y8fvb': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'pynml7sr': {
      'en': 'Gaurdian Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    'ie2e3opa': {
      'en': 'Guardian Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    '2lbl008g': {
      'en': 'Guardian Relation',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    '82wec3lg': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    '2ypnk1tt': {
      'en': 'Sibling Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    '5vs6ypqy': {
      'en': 'Sibling Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    'vvswt372': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'hu1ngxzs': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'wxioxyco': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    '1w1j57m5': {
      'en': 'Faculty Details',
      'gu': 'ફેકલ્ટી વિગતો',
      'hi': 'संकाय विवरण',
      'mr': 'विद्याशाखा तपशील',
      'ta': 'ஆசிரிய விவரங்கள்',
    },
    'spa7oula': {
      'en': 'Qualification',
      'gu': 'લાયકાત',
      'hi': 'योग्यता',
      'mr': 'पात्रता',
      'ta': 'தகுதி',
    },
    '9sk7levv': {
      'en': 'Designation',
      'gu': 'હોદ્દો',
      'hi': 'पद का नाम',
      'mr': 'पदनाम',
      'ta': 'பதவி',
    },
    'c742r7aq': {
      'en': 'Resume',
      'gu': 'ફરી શરુ કરવું',
      'hi': 'फिर शुरू करना',
      'mr': 'पुन्हा सुरू करा',
      'ta': 'தற்குறிப்பு',
    },
    'gn6zyprq': {
      'en': 'Authentication Details',
      'gu': 'પ્રમાણીકરણ વિગતો',
      'hi': 'प्रमाणीकरण विवरण',
      'mr': 'प्रमाणीकरण तपशील',
      'ta': 'அங்கீகார விவரங்கள்',
    },
    '52r4hlsh': {
      'en': 'Email ',
      'gu': 'ઈમેલ',
      'hi': 'ईमेल',
      'mr': 'ईमेल',
      'ta': 'மின்னஞ்சல்',
    },
    'x21z0nv6': {
      'en': 'Provide unique email ',
      'gu': 'કૃપા કરીને અનન્ય ઇમેઇલ સરનામું પ્રદાન કરો',
      'hi': 'कृपया अद्वितीय ईमेल पता प्रदान करें',
      'mr': 'कृपया अद्वितीय ईमेल पत्ता प्रदान करा',
      'ta': 'தனிப்பட்ட மின்னஞ்சல் முகவரியை வழங்கவும்',
    },
    'szq8apja': {
      'en': 'Password',
      'gu': 'પાસવર્ડ',
      'hi': 'पासवर्ड',
      'mr': 'पासवर्ड',
      'ta': 'கடவுச்சொல்',
    },
    '94cadz89': {
      'en': 'Provide password',
      'gu': 'પાસવર્ડ આપો',
      'hi': 'पासवर्ड प्रदान करें',
      'mr': 'पासवर्ड द्या',
      'ta': 'கடவுச்சொல்லை வழங்கவும்',
    },
    'cz7ndmfq': {
      'en': 'Created by',
      'gu': 'પાસવર્ડ',
      'hi': 'पासवर्ड',
      'mr': 'पासवर्ड',
      'ta': 'கடவுச்சொல்',
    },
    'tg4kquk1': {
      'en': 'Provide password',
      'gu': 'પાસવર્ડ આપો',
      'hi': 'पासवर्ड प्रदान करें',
      'mr': 'पासवर्ड द्या',
      'ta': 'கடவுச்சொல்லை வழங்கவும்',
    },
    '8ws487jw': {
      'en': 'Create Account',
      'gu': 'ખાતું બનાવો',
      'hi': 'खाता बनाएं',
      'mr': 'खाते तयार करा',
      'ta': 'உங்கள் கணக்கை துவங்குங்கள்',
    },
    'ib2ef6y6': {
      'en': 'Create Profile',
      'gu': 'પ્રોફાઇલ બનાવો',
      'hi': 'प्रोफ़ाइल बनाने',
      'mr': 'प्रोफाइल तयार करा',
      'ta': 'சுயவிவரத்தை உருவாக்கவும்',
    },
  },
  // welcome
  {
    'vysp76bg': {
      'en': 'Department of Special Education, SNDT Women’s University',
      'gu': 'વિશેષ શિક્ષણ વિભાગ, SNDT',
      'hi': 'विशेष शिक्षा विभाग, एसएनडीटी',
      'mr': 'विशेष शिक्षण विभाग, SNDT',
      'ta': 'சிறப்புக் கல்வித் துறை, SNDT',
    },
    'mwnx9sp9': {
      'en': 'Get Started',
      'gu': 'શરૂ કરો',
      'hi': 'शुरू हो जाओ',
      'mr': 'सुरु करूया',
      'ta': 'தொடங்குங்கள்',
    },
    'ejpjb1n9': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // HomeCopy2
  {
    'oz50rt0i': {
      'en': 'Timetable',
      'gu': 'અનુસૂચિ',
      'hi': 'अनुसूची',
      'mr': 'वेळापत्रक',
      'ta': 'அட்டவணை',
    },
    'c4j6vcfc': {
      'en': 'Schedule Student',
      'gu': 'અનુસૂચિ',
      'hi': 'अनुसूची',
      'mr': 'वेळापत्रक',
      'ta': 'அட்டவணை',
    },
    'scfi4vmj': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'kugc9ood': {
      'en': 'Messages',
      'gu': 'સંદેશાઓ',
      'hi': 'संदेशों',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'twwp5mmv': {
      'en': 'Student Resources',
      'gu': 'વિદ્યાર્થી સંસાધનો',
      'hi': 'छात्र संसाधन',
      'mr': 'विद्यार्थी संसाधने',
      'ta': 'மாணவர் வளங்கள்',
    },
    'ofdfkcig': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'vxcvwi02': {
      'en': 'Notice',
      'gu': 'નોટિસ',
      'hi': 'सूचना',
      'mr': 'लक्ष द्या',
      'ta': 'கவனிக்கவும்',
    },
    '5j5kba1e': {
      'en': '1',
      'gu': '1',
      'hi': '1',
      'mr': '१',
      'ta': '1',
    },
    'r6dgci9h': {
      'en': 'Posts',
      'gu': 'પોસ્ટ્સ',
      'hi': 'पदों',
      'mr': 'पोस्ट',
      'ta': 'இடுகைகள்',
    },
    '9stosz6j': {
      'en': 'Student Profile',
      'gu': 'વિદ્યાર્થી પ્રોફાઇલ',
      'hi': 'छात्र प्रोफाइल',
      'mr': 'विद्यार्थी प्रोफाइल',
      'ta': 'மாணவர் சுயவிவரம்',
    },
    '8y400ku2': {
      'en': 'Gallery',
      'gu': 'ગેલેરી',
      'hi': 'गैलरी',
      'mr': 'गॅलरी',
      'ta': 'கேலரி',
    },
    '5xgn8qtt': {
      'en': 'Faculty',
      'gu': 'ફેકલ્ટી',
      'hi': 'संकाय',
      'mr': 'विद्याशाखा',
      'ta': 'ஆசிரியர்',
    },
    'mhwvrjz6': {
      'en': 'Home',
      'gu': 'ઘર',
      'hi': 'घर',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'வீடு',
    },
  },
  // update_account_details
  {
    'j61gf5u7': {
      'en': 'parent',
      'gu': 'પુરુષ',
      'hi': 'पुरुष',
      'mr': 'पुरुष',
      'ta': 'ஆண்',
    },
    '714hzd5o': {
      'en': 'teacher',
      'gu': 'સ્ત્રી',
      'hi': 'महिला',
      'mr': 'स्त्री',
      'ta': 'பெண்',
    },
    '8tl5gcxd': {
      'en': 'Select role',
      'gu': 'લિંગ પસંદ કરો',
      'hi': 'लिंग चुनें',
      'mr': 'लिंग निवडा',
      'ta': 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
    },
    'cgwujrst': {
      'en': 'Name',
      'gu': 'નામ',
      'hi': 'नाम',
      'mr': 'नाव',
      'ta': 'பெயர்',
    },
    'ali0s9em': {
      'en': 'Male',
      'gu': 'પુરુષ',
      'hi': 'पुरुष',
      'mr': 'पुरुष',
      'ta': 'ஆண்',
    },
    'a4o8gp7e': {
      'en': 'Female',
      'gu': 'સ્ત્રી',
      'hi': 'महिला',
      'mr': 'स्त्री',
      'ta': 'பெண்',
    },
    'fmg01wqx': {
      'en': 'Select Gender',
      'gu': 'લિંગ પસંદ કરો',
      'hi': 'लिंग चुनें',
      'mr': 'लिंग निवडा',
      'ta': 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
    },
    '23xybfcq': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    '6dt4zhv1': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'adi26fo0': {
      'en': 'Place & Country of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'bpks166e': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    '4h0di289': {
      'en': 'Aadhar card no.',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'kjenqe0s': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'rzq3rvxd': {
      'en': 'Blood Group',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    '3yi736mz': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'ih202ev4': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    'x9h7pr5f': {
      'en': 'Number which is to be conntected with portal',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'qw46jj9e': {
      'en': 'Address',
      'gu': 'સરનામું',
      'hi': 'पता',
      'mr': 'पत्ता',
      'ta': 'முகவரி',
    },
    'mlz6t331': {
      'en': 'Identity Proof',
      'gu': 'ઓળખ પુરાવો',
      'hi': 'पहचान प्रमाण',
      'mr': 'ओळख पुरावा',
      'ta': 'அடையாளச் சான்று',
    },
    'gqxbuijq': {
      'en': 'Student Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    '9ce2e92s': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    'opma7aq9': {
      'en': 'Disability',
      'gu': 'અપંગતા',
      'hi': 'विकलांगता',
      'mr': 'दिव्यांग',
      'ta': 'இயலாமை',
    },
    'kw7rmktk': {
      'en': 'Medical Paper',
      'gu': 'મેડિકલ પેપર',
      'hi': 'मेडिकल पेपर',
      'mr': 'वैद्यकीय पेपर',
      'ta': 'மருத்துவ தாள்',
    },
    '095fuo0y': {
      'en': 'Father\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    'kqoc5aiw': {
      'en': 'Father Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    'vmk7vree': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'p926f91e': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '8yljq49j': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'qj8pgp37': {
      'en': 'Mother\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    't67tpcij': {
      'en': 'Mother Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    'cij4kffy': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'vl9z0k9o': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'ph8x7zi3': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '4za92c5o': {
      'en': 'Gaurdian Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    'unes1fqo': {
      'en': 'Guardian Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    'akdf8kwb': {
      'en': 'Guardian Relation',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    'e7b0dsha': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    'cy99t8s7': {
      'en': 'Sibling Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    'bvouphi4': {
      'en': 'Sibling Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    'leb2assy': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    '2m4cjqtm': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'xdjwm8h3': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    'avx4zhnc': {
      'en': 'Faculty Details',
      'gu': 'ફેકલ્ટી વિગતો',
      'hi': 'संकाय विवरण',
      'mr': 'विद्याशाखा तपशील',
      'ta': 'ஆசிரிய விவரங்கள்',
    },
    '6tsggm7n': {
      'en': 'Qualification',
      'gu': 'લાયકાત',
      'hi': 'योग्यता',
      'mr': 'पात्रता',
      'ta': 'தகுதி',
    },
    'sxmzonlx': {
      'en': 'Designation',
      'gu': 'હોદ્દો',
      'hi': 'पद का नाम',
      'mr': 'पदनाम',
      'ta': 'பதவி',
    },
    '4yxuju6i': {
      'en': 'Resume',
      'gu': 'ફરી શરુ કરવું',
      'hi': 'फिर शुरू करना',
      'mr': 'पुन्हा सुरू करा',
      'ta': 'தற்குறிப்பு',
    },
    'nhuy6vte': {
      'en': 'Update Account',
      'gu': 'ખાતું બનાવો',
      'hi': 'खाता बनाएं',
      'mr': 'खाते तयार करा',
      'ta': 'உங்கள் கணக்கை துவங்குங்கள்',
    },
    'ez6dmqux': {
      'en': 'Update Profile',
      'gu': 'પ્રોફાઇલ બનાવો',
      'hi': 'प्रोफ़ाइल बनाने',
      'mr': 'प्रोफाइल तयार करा',
      'ta': 'சுயவிவரத்தை உருவாக்கவும்',
    },
  },
  // view_profile_details
  {
    '2xf65m22': {
      'en': 'Name',
      'gu': 'નામ',
      'hi': 'नाम',
      'mr': 'नाव',
      'ta': 'பெயர்',
    },
    'wjqhi6hu': {
      'en': 'Gender',
      'gu': 'નામ',
      'hi': 'नाम',
      'mr': 'नाव',
      'ta': 'பெயர்',
    },
    'bccalo4i': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'of086npo': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'yhn2fgpp': {
      'en': 'Place & Country of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    '61gpjtxj': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'yg6iaksk': {
      'en': 'Aadhar card no.',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'yfyoen9t': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'w07cwlfn': {
      'en': 'Blood Group',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'ntevmibl': {
      'en': '',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    '4n3qk6s9': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    '9ookyo0c': {
      'en': 'Number which is to be conntected with portal',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '5aejds7p': {
      'en': 'Address',
      'gu': 'સરનામું',
      'hi': 'पता',
      'mr': 'पत्ता',
      'ta': 'முகவரி',
    },
    'y41lkh4l': {
      'en': 'Identity Proof ',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'meq1po2d': {
      'en': 'Student Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    'eptg0xq2': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    '7lhxyx8a': {
      'en': 'Disability',
      'gu': 'અપંગતા',
      'hi': 'विकलांगता',
      'mr': 'दिव्यांग',
      'ta': 'இயலாமை',
    },
    'jqaz7fvt': {
      'en': 'Medical papers',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ac0xzm14': {
      'en': 'Father\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    '70wn3lbn': {
      'en': 'Father Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    '7isevdxh': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '1nkk3bge': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'y59j6izo': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'yelyluk1': {
      'en': 'Mother\'s Details',
      'gu': 'વિદ્યાર્થીની વિગતો',
      'hi': 'छात्र विवरण',
      'mr': 'विद्यार्थी तपशील',
      'ta': 'மாணவர் விவரங்கள்',
    },
    'g6nq0dcv': {
      'en': 'Mother Name',
      'gu': 'પિતૃ નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकांचे नाव',
      'ta': 'பெற்றோர் பெயர்',
    },
    'ay4qd7c1': {
      'en': 'Occcupation',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    '8qmmi6l3': {
      'en': 'Phone Number',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'simtrrcj': {
      'en': 'Email ID',
      'gu': 'વ્યવસાય',
      'hi': 'पेशा',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'oqsix1x9': {
      'en': 'Gaurdian Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    'zedae2as': {
      'en': 'Guardian Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    'kmg1znwh': {
      'en': 'Guardian Relation',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    '1s3rufeq': {
      'en': 'Phone Number',
      'gu': 'ફોન નંબર',
      'hi': 'फ़ोन नंबर',
      'mr': 'फोन नंबर',
      'ta': 'தொலைபேசி எண்',
    },
    '31w9tmtx': {
      'en': 'Sibling Details',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    '2n5xaf3i': {
      'en': 'Sibling Name',
      'gu': 'વાલીનું નામ',
      'hi': 'अभिभावक का नाम',
      'mr': 'पालकाचे नाव',
      'ta': 'காப்பாளர் பெயர்',
    },
    '3omlkzci': {
      'en': 'Date of Birth',
      'gu': 'જન્મ તારીખ',
      'hi': 'जन्म की तारीख',
      'mr': 'जन्मतारीख',
      'ta': 'பிறந்த தேதி',
    },
    'rpimo8f4': {
      'en': 'dd/mm/yyyy',
      'gu': 'dd/mm/yyyy',
      'hi': 'dd/mm/yyyy',
      'mr': 'dd/mm/yyyy',
      'ta': 'dd/mm/yyyy',
    },
    'p9kh9hwz': {
      'en': 'Class Name',
      'gu': 'વર્ગનું નામ',
      'hi': 'कक्षा का नाम',
      'mr': 'वर्गाचे नाव',
      'ta': 'வகுப்பின் பெயர்',
    },
    '7m8r59g0': {
      'en': 'Faculty Details',
      'gu': 'ફેકલ્ટી વિગતો',
      'hi': 'संकाय विवरण',
      'mr': 'विद्याशाखा तपशील',
      'ta': 'ஆசிரிய விவரங்கள்',
    },
    'oqqjfo3u': {
      'en': 'Qualification',
      'gu': 'લાયકાત',
      'hi': 'योग्यता',
      'mr': 'पात्रता',
      'ta': 'தகுதி',
    },
    'yq6mdbjq': {
      'en': 'Designation',
      'gu': 'હોદ્દો',
      'hi': 'पद का नाम',
      'mr': 'पदनाम',
      'ta': 'பதவி',
    },
    'cdhf756n': {
      'en': 'Faculty Resume',
      'gu': 'ગાર્ડિયન વિગતો',
      'hi': 'गौरडियन विवरण',
      'mr': 'गार्डियन तपशील',
      'ta': 'கார்டியன் விவரங்கள்',
    },
    '8jpihb06': {
      'en': 'Your Authentication Details',
      'gu': 'પ્રમાણીકરણ વિગતો',
      'hi': 'प्रमाणीकरण विवरण',
      'mr': 'प्रमाणीकरण तपशील',
      'ta': 'அங்கீகார விவரங்கள்',
    },
    'a2qm2cgq': {
      'en': 'Email ',
      'gu': 'ઈમેલ',
      'hi': 'ईमेल',
      'mr': 'ईमेल',
      'ta': 'மின்னஞ்சல்',
    },
    'xb6cdnur': {
      'en': 'Provide unique email ',
      'gu': 'કૃપા કરીને અનન્ય ઇમેઇલ સરનામું પ્રદાન કરો',
      'hi': 'कृपया अद्वितीय ईमेल पता प्रदान करें',
      'mr': 'कृपया अद्वितीय ईमेल पत्ता प्रदान करा',
      'ta': 'தனிப்பட்ட மின்னஞ்சல் முகவரியை வழங்கவும்',
    },
    'j2vts7kj': {
      'en': 'Password',
      'gu': 'પાસવર્ડ',
      'hi': 'पासवर्ड',
      'mr': 'पासवर्ड',
      'ta': 'கடவுச்சொல்',
    },
    'uxbbi4fk': {
      'en': 'Provide password',
      'gu': 'પાસવર્ડ આપો',
      'hi': 'पासवर्ड प्रदान करें',
      'mr': 'पासवर्ड द्या',
      'ta': 'கடவுச்சொல்லை வழங்கவும்',
    },
    'tmbicyeu': {
      'en': 'Log Out',
      'gu': 'ખાતું બનાવો',
      'hi': 'खाता बनाएं',
      'mr': 'खाते तयार करा',
      'ta': 'உங்கள் கணக்கை துவங்குங்கள்',
    },
    '36603tjn': {
      'en': 'View Profile Details',
      'gu': 'પ્રોફાઇલ બનાવો',
      'hi': 'प्रोफ़ाइल बनाने',
      'mr': 'प्रोफाइल तयार करा',
      'ta': 'சுயவிவரத்தை உருவாக்கவும்',
    },
  },
  // chat_DetailsOverlay
  {
    'as68kded': {
      'en': 'Chat Details',
      'gu': 'ચેટ વિગતો',
      'hi': 'चैट विवरण',
      'mr': 'गप्पा तपशील',
      'ta': 'அரட்டை விவரங்கள்',
    },
    'h5vht27t': {
      'en': 'Group Chat Name: ',
      'gu': 'જૂથ ચેટ ID:',
      'hi': 'समूह चैट आईडी:',
      'mr': 'गट चॅट आयडी:',
      'ta': 'குழு அரட்டை ஐடி:',
    },
    'yrtwirn9': {
      'en': 'In this chat',
      'gu': 'આ ચેટમાં',
      'hi': 'इस चैट में',
      'mr': 'या गप्पांमध्ये',
      'ta': 'இந்த அரட்டையில்',
    },
    'bh2xt0r6': {
      'en': 'Close',
      'gu': 'બંધ',
      'hi': 'बंद करना',
      'mr': 'बंद',
      'ta': 'நெருக்கமான',
    },
  },
  // chat_ThreadComponent
  {
    'dgo0negl': {
      'en': 'Start typing here...',
      'gu': 'અહીં ટાઇપ કરવાનું શરૂ કરો...',
      'hi': 'यहां टाइप करना प्रारंभ करें...',
      'mr': 'येथे टाइप करणे सुरू करा...',
      'ta': 'இங்கே தட்டச்சு செய்யத் தொடங்கு...',
    },
    'tzua9b42': {
      'en': 'You must enter a message...',
      'gu': 'તમારે એક સંદેશ દાખલ કરવો પડશે...',
      'hi': 'आपको एक संदेश दर्ज करना होगा...',
      'mr': 'आपण एक संदेश प्रविष्ट करणे आवश्यक आहे...',
      'ta': 'நீங்கள் ஒரு செய்தியை உள்ளிட வேண்டும்...',
    },
    '3zy6vcrx': {
      'en': 'Please choose an option from the dropdown',
      'gu': 'કૃપા કરીને ડ્રોપડાઉનમાંથી એક વિકલ્પ પસંદ કરો',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'mr': 'कृपया ड्रॉपडाउनमधून एक पर्याय निवडा',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
    },
  },
  // user_ListSmall
  {
    'k5i07tsm': {
      'en': 'ME',
      'gu': 'ME',
      'hi': 'मुझे',
      'mr': 'मी',
      'ta': 'ME',
    },
  },
  // deleteDialog
  {
    'ziuwi8a6': {
      'en': 'Options',
      'gu': 'વિકલ્પો',
      'hi': 'विकल्प',
      'mr': 'पर्याय',
      'ta': 'விருப்பங்கள்',
    },
    'dffd82p4': {
      'en': 'Invite Users',
      'gu': 'વપરાશકર્તાઓને આમંત્રિત કરો',
      'hi': 'उपयोगकर्ताओं को आमंत्रित करें',
      'mr': 'वापरकर्त्यांना आमंत्रित करा',
      'ta': 'பயனர்களை அழைக்கவும்',
    },
    '80e3tj9o': {
      'en': 'Delete Chat',
      'gu': 'ચેટ કાઢી નાખો',
      'hi': 'चैट हटाएँ',
      'mr': 'चॅट हटवा',
      'ta': 'அரட்டையை நீக்கு',
    },
    'k1yx7wl7': {
      'en': 'Confirm Delete',
      'gu': 'કાઢી નાખવાની પુષ્ટિ કરો',
      'hi': 'हटाने की पुष्टि करें',
      'mr': 'हटविण्याची पुष्टी करा',
      'ta': 'நீக்குவதை உறுதிப்படுத்தவும்',
    },
    'd6nngj3c': {
      'en': 'You can\'t undo this action.',
      'gu': 'તમે આ ક્રિયાને પૂર્વવત્ કરી શકતા નથી.',
      'hi': 'आप इस क्रिया को पूर्ववत नहीं कर सकते.',
      'mr': 'तुम्ही ही क्रिया पूर्ववत करू शकत नाही.',
      'ta': 'இந்தச் செயலைச் செயல்தவிர்க்க முடியாது.',
    },
    'eqgge179': {
      'en': 'Delete',
      'gu': 'કાઢી નાખો',
      'hi': 'मिटाना',
      'mr': 'हटवा',
      'ta': 'அழி',
    },
  },
  // userList_member
  {
    'e01wnlo4': {
      'en': 'ME',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // user_List
  {
    '0d1picgh': {
      'en': 'Select Students',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'fzr491a1': {
      'en': 'Select a student from the list below to continue.',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '2e0yl7of': {
      'en': 'Close',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // GrpChat_rename
  {
    's86enz87': {
      'en': 'Edit Group Name',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'rqjcjwt2': {
      'en': 'Current name',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'bytmi34o': {
      'en': 'Enter new name',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'l2wqwtnc': {
      'en': 'Update',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // pin_secure
  {
    'rkzho6d9': {
      'en': 'Enter security PIN below',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'qneh1buf': {
      'en': 'Only authorized users are allowed to make any changes !',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'u2jpuu3a': {
      'en': 'Cancel',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '74962f3l': {
      'en': 'Verify',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // pin_secure_AddUser
  {
    '5nvhj5up': {
      'en': 'Enter security PIN below',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '4d1dnnfm': {
      'en': 'Only authorized users are allowed to create new accounts !',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '88w29upr': {
      'en': 'Cancel',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'idngcxbb': {
      'en': 'Verify',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // pin_secure_updateUserDetails
  {
    '2feu6kun': {
      'en': 'Enter security PIN below',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '6nxub6td': {
      'en': 'Only authorized users are allowed to create new accounts !',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'zjx23ayu': {
      'en': 'Cancel',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'cnjjr0p9': {
      'en': 'Verify',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
  // Miscellaneous
  {
    'qh47p6sp': {
      'en':
          'In order to take a picture or video, this app requires permission to access the camera.',
      'gu':
          'ચિત્ર અથવા વિડિયો લેવા માટે, આ એપ્લિકેશનને કેમેરાને ઍક્સેસ કરવાની પરવાનગીની જરૂર છે.',
      'hi':
          'चित्र या वीडियो लेने के लिए, इस ऐप को कैमरे तक पहुंचने की अनुमति की आवश्यकता होती है।',
      'mr':
          'चित्र किंवा व्हिडिओ घेण्यासाठी, या ॲपला कॅमेरा ऍक्सेस करण्याची परवानगी आवश्यक आहे.',
      'ta':
          'படம் அல்லது வீடியோ எடுக்க, இந்த பயன்பாட்டிற்கு கேமராவை அணுக அனுமதி தேவை.',
    },
    '0oivz66o': {
      'en':
          'In order to record audio for video, this app requires permission to access the microphone.',
      'gu':
          'વિડિઓ માટે ઑડિઓ રેકોર્ડ કરવા માટે, આ એપ્લિકેશનને માઇક્રોફોનને ઍક્સેસ કરવાની પરવાનગીની જરૂર છે.',
      'hi':
          'वीडियो के लिए ऑडियो रिकॉर्ड करने के लिए, इस ऐप को माइक्रोफ़ोन तक पहुंचने की अनुमति की आवश्यकता होती है।',
      'mr':
          'व्हिडिओसाठी ऑडिओ रेकॉर्ड करण्यासाठी, या ॲपला मायक्रोफोनमध्ये प्रवेश करण्याची परवानगी आवश्यक आहे.',
      'ta':
          'வீடியோவிற்கான ஆடியோவைப் பதிவுசெய்ய, இந்த பயன்பாட்டிற்கு மைக்ரோஃபோனை அணுக அனுமதி தேவை.',
    },
    'jlolhr64': {
      'en':
          'In order to upload data, this app requires permission to access the photo library.',
      'gu':
          'ડેટા અપલોડ કરવા માટે, આ એપ્લિકેશનને ફોટો લાઇબ્રેરીને ઍક્સેસ કરવાની પરવાનગીની જરૂર છે.',
      'hi':
          'डेटा अपलोड करने के लिए, इस ऐप को फोटो लाइब्रेरी तक पहुंचने की अनुमति की आवश्यकता होती है।',
      'mr':
          'डेटा अपलोड करण्यासाठी, या ॲपला फोटो लायब्ररीमध्ये प्रवेश करण्याची परवानगी आवश्यक आहे.',
      'ta':
          'தரவைப் பதிவேற்ற, இந்த பயன்பாட்டிற்கு புகைப்பட நூலகத்தை அணுக அனுமதி தேவை.',
    },
    'pv2fdo34': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'myvziubg': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    's2h8w79m': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'fpjqchps': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'h6d8kxue': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'et9msy26': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'udgsd3h4': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'plwanwvn': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'q6v2i352': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '5i4d86br': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    've01h4pz': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'byifkx7o': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '6b3vssa5': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'n85q00c1': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'cguqr4um': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'nid9sm5g': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'ic9rzlus': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    '9mwpcc14': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'glzw3jfq': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    's58xkihj': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'n85l943h': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'mje1ttgv': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'tp29h0z3': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'gl7vptrl': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
    'r16zla1h': {
      'en': '',
      'gu': '',
      'hi': '',
      'mr': '',
      'ta': '',
    },
  },
].reduce((a, b) => a..addAll(b));
